[package]
name = "argh"
version = "0.1.4"
authors = ["Taylor Cramer <cramertj@google.com>", "Benjamin Brittain<bwb@google.com>"]
edition = "2018"
readme = "README.md"
keywords = ["args", "arguments", "derive", "cli"]
license = "BSD-3-Clause"
description = "Derive-based argument parser optimized for code size"
repository = "https://github.com/google/argh"

[dependencies]
argh_shared = { version = "0.1.1", path = "./argh_shared" }
argh_derive = { version = "0.1.1", path = "./argh_derive" }
